# Generated by Django 6.0.3 on 2026-04-30 15:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, default='', max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.CharField(blank=True, default='', max_length=200)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_index=True, default='activo', max_length=10)),
                ('fechaRegistro', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(db_column='idMarca', primary_key=True, serialize=False)),
                ('nombreMarca', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('envio', models.IntegerField(default=0)),
                ('fechaRegistro', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='TipoProductos',
            fields=[
                ('idTipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(db_column='nombre', db_index=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', default='')),
            ],
            options={
                'verbose_name': 'tipo_producto',
                'verbose_name_plural': 'tipos_productos',
                'db_table': 'tipoproducto',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('idUnidad', models.AutoField(db_column='idUnidad', primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(db_column='nombreUnidad', db_index=True, max_length=100)),
                ('abreviatura', models.CharField(blank=True, db_column='abreviatura', default='-', max_length=10)),
            ],
            options={
                'verbose_name': 'unidad_medida',
                'verbose_name_plural': 'unidades_medida',
                'db_table': 'unidadmedida',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Completada', 'Completada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('info', 'Información'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=20)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación email',
                'verbose_name_plural': 'notificaciones email',
                'db_table': 'notificacion_email',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('estado_pedido', models.CharField(max_length=150)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Código de barras')),
                ('idMarca', models.ForeignKey(db_column='idMarca', on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('idTipo', models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.CASCADE, to='app.tipoproductos')),
                ('idUnidad', models.ForeignKey(db_column='idUnidad', on_delete=django.db.models.deletion.CASCADE, to='app.unidadmedida')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
                'unique_together': {('nombre', 'idMarca', 'idTipo')},
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('fechaCompra', models.DateField(db_column='fecha', default=datetime.datetime.now)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada')], default='Pendiente', max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('Producto', models.ForeignKey(blank=True, db_column='Producto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
                ('Proveedor', models.ForeignKey(db_column='Proveedor_id', on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'db_table': 'compra',
                'ordering': ['-fechaCompra'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReporte', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('idCompra', models.ForeignKey(blank=True, db_column='idCompra', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compra')),
                ('idPedido', models.ForeignKey(blank=True, db_column='idPedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pedidos')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('idVenta', models.ForeignKey(blank=True, db_column='idVenta', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.venta')),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(blank=True, db_column='producto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
